// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxscqxkrtbsximfkgbcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4c2NxeGtydGJzeGltZmtnYmNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NDYzODUsImV4cCI6MjA1OTAyMjM4NX0.xiFpuLxczmY_QNvv7cE6Jez84PmMKpkAeMIhctZCNYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);